<?php

use App\Console\Commands\ApplyOverdueFines;
use App\Models\Company;
use App\Services\FineService;
use Database\Seeders\MasterSetupSeeder;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

Artisan::command('sync:permissions', function () {

    $hardcodedPermissions = [
        "view master setups",
        "create master setups",
        "edit master setups",
        "delete master setups",
        "view member entries",
        "create member entries",
        "edit member entries",
        "delete member entries",
        "view meter issues",
        "create meter issues",
        "edit meter issues",
        "delete meter issues",
        "view other charges",
        "create other charges",
        "edit other charges",
        "delete other charges",
        "view discounts and fines",
        "create discounts and fines",
        "edit discounts and fines",
        "delete discounts and fines",
        "view rates and capacities",
        "create rates and capacities",
        "edit rates and capacities",
        "delete rates and capacities",
        "view tariff setup",
        "create tariff setup",
        "edit tariff setup",
        "delete tariff setup",
        "view meter reading entries",
        "create meter reading entries",
        "edit meter reading entries",
        "delete meter reading entries",
        "view other income receipts",
        "create other income receipts",
        "edit other income receipts",
        "delete other income receipts",
        "transfer entries",
        "view transfer entries",
        "view opening meter deposit entries",
        "create opening meter deposit entries",
        "edit opening meter deposit entries",
        "delete opening meter deposit entries",
        "view share opening entries",
        "create share opening entries",
        "edit share opening entries",
        "delete share opening entries",
        "view opening mahasul balance entries",
        "create opening mahasul balance entries",
        "edit opening mahasul balance entries",
        "delete opening mahasul balance entries",
        "view change meter issues",
        "change meter issues",
        "edit change meter issues",
        "delete change meter issues",
        "view share entries",
        "create share entries",
        "edit share entries",
        "delete share entries",
        "view deposit entries",
        "create deposit entries",
        "edit deposit entries",
        "delete deposit entries",
        "cancel deposit entries",
        "view upgrade meter capacity",
        "create upgrade entries",
        "cancel upgrade meter",
        "edit upgrade meter capacity",
        "delete upgrade meter capacity",
        "view share return",
        "create share return",
        "edit share return",
        "delete share return",
        "view deposit return",
        "create deposit return",
        "edit deposit return",
        "delete deposit return",
        "cancel deposit return",
        "view mahsul receipts",
        "create mahsul receipts",
        "edit mahsul receipts",
        "delete mahsul receipts",
        "view meter insurance",
        "create meter insurance",
        "edit meter insurance",
        "delete meter insurance",
        "view advance payment",
        "create advance payment",
        "edit advance payment",
        "delete advance payment",
        "view non member payment",
        "create non member payment",
        "edit non member payment",
        "delete non member payment",
        "view fine post",
        "create fine post",
        "edit fine post",
        "delete fine post",
        "view nea purchase",
        "create nea purchase",
        "edit nea purchase",
        "delete nea purchase",
        "view nea payment",
        "create nea payment",
        "edit nea payment",
        "delete nea payment",
        "view measure units",
        "create measure units",
        "edit measure units",
        "delete measure units",
        "view main groups",
        "create main groups",
        "edit main groups",
        "delete main groups",
        "view sub groups",
        "create sub groups",
        "edit sub groups",
        "delete sub groups",
        "view account groups",
        "create account groups",
        "edit account groups",
        "delete account groups",
        "view account heads",
        "create account heads",
        "edit account heads",
        "delete account heads",
        "view fixed asset groups",
        "create fixed asset groups",
        "edit fixed asset groups",
        "delete fixed asset groups",
        "view fixed asset accounts",
        "create fixed asset accounts",
        "edit fixed asset accounts",
        "delete fixed asset accounts",
        "view voucher summaries",
        "create voucher summaries",
        "edit voucher summaries",
        "delete voucher summaries",
        "view voucher summary details",
        "create voucher summary details",
        "edit voucher summary details",
        "delete voucher summary details",
        "view purchases",
        "create purchases",
        "edit purchases",
        "delete purchases",
        "view products",
        "create products",
        "edit products",
        "delete products",
        "view product categories",
        "create product categories",
        "edit product categories",
        "delete product categories",
        "view product subcategories",
        "create product subcategories",
        "edit product subcategories",
        "delete product subcategories",
        "view purchase returns",
        "create purchase returns",
        "edit purchase returns",
        "delete purchase returns",
        "view sales",
        "create sales",
        "edit sales",
        "delete sales",
        "view sale returns",
        "create sale returns",
        "edit sale returns",
        "delete sale returns",
        "view member report",
        "view meter issue report",
        "view meter issue transfer report",
        "view meter deposit report",
        "view opening meter deposit report",
        "create opening entries",
        "view meter reading report",
        "view nea payment report",
        "view voucher summary",
        "view journal voucher",
        "create journal voucher",
        "edit journal voucher",
        "delete journal voucher",
        "view journal voucher transaction",
        "create journal voucher transaction",
        "edit journal voucher transaction",
        "delete journal voucher transaction",
        "view nea purchase report",
        "view opening mahasul balance report",
        "view change meter report",
        "view nea report",
        "view other income head report",
        "view sales return",
        "create sales return",
        "edit sales return",
        "delete sales return",


        "view member details",
        "view share details",
        "view deposit details",
        "view other income details",
        "view meter reading details",
        "view mahsul details",
        "view nea leakage report",
        "view absent ledger report",
        "view customer ledger report",
        "view voucher report",
        "cancel voucher report",
        "view disability discount",
        "update disability discount",
        "sync data",
        "view wiring persons",
        "create wiring persons",
        "edit wiring persons",
        "delete wiring persons",
        "view Fines",
        "view rebate discount",
        "create rebate discount",
        "edit rebate discount",
        "delete rebate discount",


    ];

    foreach ($hardcodedPermissions as $permissionName) {
        Permission::firstOrCreate([
            'name' => $permissionName,
            'guard_name' => 'api',
        ]);
    }

    $this->info(' All permissions synced successfully in the main database!');
})->describe('Sync all hardcoded permissions in the main (default) database');


Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
});


Schedule::command('fines:apply')
    ->dailyAt('00:00') 
    ->withoutOverlapping()
    ->onOneServer();